var db = require("../models"); //../ is there to back out of current routes folder; then require modules to post the todos in the database

exports.getTodos = function(req,res){  // this route gives us all the items which are in the data base
    db.Todo.find()
    .then(function(todos){
        res.json(todos);
    })
    .catch(function(err){
        res.send(err);
    });
};


exports.createTodo = function(req,res){ // this routes allows us to paste additional item in database
    db.Todo.create(req.body)
    .then(function(newTodo){
        res.json(newTodo);
    })
    .catch(function(err){
        res.send(err);
    });
};

exports.getTodo = function(req,res){  // this routes give us specific information about on particular item in todo list
    db.Todo.findById(req.params.todoId) // function req.params.todoId lets us access the id of the stored items -- id generated by mongo directly
    .then(function(foundTodo){
        res.json(foundTodo);
    })
    .catch(function(err){
        res.send(err);
    });
};

exports.updateTodo = function(req,res){
    db.Todo.findOneAndUpdate({_id: req.params.todoId}, req.body, {new: true})  // new: true doesn't send you old version as by default from mongoose but sends you new, updated version
    .then(function(todo){
        res.json(todo);
    })
    .catch(function(err){
        res.send(err);
    });
};

exports.deleteTodo = function(req,res){
    db.Todo.remove({_id: req.params.todoId})
    .then(function(){
        res.json({message: 'we deleted it!'});
    })
    .catch(function(err){
        res.send(err);
    });
};

module.exports = exports;